// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXUvrZ1X0JrZNtkDQeqWdeEsgrsyOtV8k',
    appId: '1:868844482890:web:2ba479c2011212756351b3',
    messagingSenderId: '868844482890',
    projectId: 'book-reviews-app-f205e',
    authDomain: 'book-reviews-app-f205e.firebaseapp.com',
    storageBucket: 'book-reviews-app-f205e.firebasestorage.app',
    measurementId: 'G-31Z3HNNHHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuA2gu_dGF6n-nBRue6LnQYfbkSgVJ9kE',
    appId: '1:868844482890:android:813d52b8e7e455f56351b3',
    messagingSenderId: '868844482890',
    projectId: 'book-reviews-app-f205e',
    storageBucket: 'book-reviews-app-f205e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEZD8wvm-nOaHh60MZjGGQKTYYkw3-Zis',
    appId: '1:868844482890:ios:0365b0ac4ebfe6ba6351b3',
    messagingSenderId: '868844482890',
    projectId: 'book-reviews-app-f205e',
    storageBucket: 'book-reviews-app-f205e.firebasestorage.app',
    iosBundleId: 'com.example.bookReviewsApp',
  );
}
